title: "FoodNotes"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "https://github.com/AY2324S1-CS2103T-W10-4/tp"
github_icon: "images/github-icon.png"
favicon: "images/foodnotes.png"

plugins:
  - jemoji
